// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpg_QaeGTDDvG77UL6bR-hsck5FwZPqjo',
    appId: '1:976874423338:web:bed80f63700480a8876f53',
    messagingSenderId: '976874423338',
    projectId: 'project-3-mashael',
    authDomain: 'project-3-mashael.firebaseapp.com',
    storageBucket: 'project-3-mashael.appspot.com',
    measurementId: 'G-3HT5WZBMLQ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUk3VFhEn5xx5HPhrYXho5H7g8YDmeAI0',
    appId: '1:976874423338:ios:cc7545fd61a1b6d6876f53',
    messagingSenderId: '976874423338',
    projectId: 'project-3-mashael',
    storageBucket: 'project-3-mashael.appspot.com',
    iosClientId: '976874423338-0m5rsejiema0e3ldknr37lqanijdp7ll.apps.googleusercontent.com',
    iosBundleId: 'com.example.project3',
  );
}
